export default {
  account: 'My account',
  actions: 'Actions',
  app: 'Application',
  allPredictions: 'All bets',
  all: 'All',

  back: 'Go back',
  backHome: 'Back to homepage',

  cancel: 'Cancel',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Create',
  createAccount: 'Create my account',
  clickToPredict: 'Click to bet',
  contactEmail: 'hello@lotofoot.io',
  contactUs: 'Contact us',
  contribute: 'Contribute to this project',

  delete: 'Delete',
  description: 'Description',
  dailyMaj: 'LOTOFOOT',
  development: 'Development',

  eightFinal: 'Round of 32',
  errorPageL1: 'An error occurred while rendering this page...',
  errorPageL2: 'Back to homepage',

  final: 'Final',
  firstname: 'First name',
  finished: 'Finished',
  forgottenPassword: 'Forgot your password?',
  finishedGain: 'This bet gives you',

  games: 'Matches',
  game: 'Match',
  group: 'Group',
  groups: 'Groups',
  gamesMini: 'Matches',

  help: 'Help',
  helpMini: 'Help',
  home: 'All matches',
  homeMini: 'Matches',

  inProgress: 'In Progress',
  inProgressGain: 'For now, this bet gives you',
  illustrations: 'Illustrations',

  key: 'Key',
  knockoutPhase: 'Knockout Phase',

  lastname: 'Last name',
  logout: 'Logout',
  login: 'Log in',

  menu: 'Menu',
  modify: 'Edit',
  myPrediction: 'My bet',

  notfoundPageL1: 'The page you requested is not available...',
  notfoundPageL2: 'Back to homepage',

  ok: 'OK',

  password: 'Password',
  predictions: 'My bets',
  point: 'point',
  points: 'points',

  quarterFinal: 'Quarter-Final',

  ranking: 'General ranking',
  rankingMini: 'Ranking',
  refresh: 'Refresh',
  required: '(required)',
  recoverInitTitle: 'Forgotten password',
  recoverInitText: 'Enter your e-mail address so that we can send you a link to reset your password',
  recoverInitTitleOk: 'Check your emails',
  recoverInitTextOk: 'We successfully received your request. An email allowing you to reset your password has been sent to you at ',
  recoverInitTextOk2: 'Remember to check your spams.',
  resetPassword: 'Reset my password',
  recoverTitle: 'Choose a new password',
  rules: 'Rules',
  recoverSuccessText: 'Your password has been changed.',
  recoverSuccessAction: 'Go to the Lotofoot',
  registerSuccessText: 'Your account has been created.',
  registerSuccessAction: 'Go to the Lotofoot',

  send: 'Send',
  semiFinal: 'Semi-Final',
  sendFeedback: 'Send feedback',
  signUp: 'Sign up',

  title: 'Title',
  toCome: 'Next',
  toPredict: 'Left to bet',
  tabToPredict: 'Tap to bet',
  tooLate: 'It\'s too late, you can\'t bet on this match anymore',
  tooLate2: 'It\'s too late, all bets are closed',

  email: 'Email',
  emailExample: 'example@me.com',

  validate: 'Confirm',

  wellReceived: 'Well received!',

  ga: 'Group A',
  gb: 'Group B',
  gc: 'Group C',
  gd: 'Group D',
  ge: 'Group E',
  gf: 'Group F',
  gg: 'Group G',
  gh: 'Group H',

  p1: '1/8',
  p2: '1/4',
  p3: '1/2',
  p4: 'Final',

  a1: '1st Group A',
  a2: '2nd Group A',
  b1: '1st Group B',
  b2: '2nd Group B',
  c1: '1st Group C',
  c2: '2nd Group C',
  d1: '1st Group D',
  d2: '2nd Group D',
  e1: '1st Group E',
  e2: '2nd Group E',
  f1: '1st Group F',
  f2: '2nd Group F',
  g1: '1st Group G',
  g2: '2nd Group G',
  h1: '1st Group H',
  h2: '2nd Group H',

  acd3: '3rd Group A, C or D',
  bef3: '3rd Group B, E or F',
  cde3: '3rd Group C, D or E',
  abf3: '3rd Group A, B or F',

  w37: 'Winner match 37',
  w38: 'Winner match 38',
  w39: 'Winner match 39',
  w40: 'Winner match 40',
  w41: 'Winner match 41',
  w42: 'Winner match 42',
  w43: 'Winner match 43',
  w44: 'Winner match 44',
  w45: 'Winner match 45',
  w46: 'Winner match 46',
  w47: 'Winner match 47',
  w48: 'Winner match 48',
  w49: 'Winner match 49',
  w50: 'Winner match 50',
  w51: 'Winner match 41',
  w52: 'Winner match 42',
  w53: 'Winner match 43',
  w54: 'Winner match 44',
  w55: 'Winner match 45',
  w56: 'Winner match 46',
  w57: 'Winner match 47',
  w58: 'Winner match 48',
  w59: 'Winner match 49',
  w60: 'Winner match 50',
  w61: 'Winner match 50',
  w62: 'Winner match 50',
  l61: 'Loser match 50',
  l62: 'Loser match 50',

  albania: 'Albania',
  argentina: 'Argentina',
  australia: 'Australia',
  austria: 'Austria',
  belgium: 'Belgium',
  brazil: 'Brazil',
  colombia: 'Colombia',
  costarica: 'Costa Rica',
  croatia: 'Croatia',
  czechrepublic: 'Czech Republic',
  denmark: 'Denmark',
  egypt: 'Egypt',
  england: 'England',
  france: 'France',
  germany: 'Germany',
  hungary: 'Hungary',
  iceland: 'Iceland',
  iran: 'Iran',
  ireland: 'Ireland',
  italy: 'Italy',
  japan: 'Japan',
  mexico: 'Mexico',
  morocco: 'Morocco',
  nigeria: 'Nigeria',
  northernireland: 'Northern Ireland',
  panama: 'Panama',
  peru: 'Peru',
  poland: 'Poland',
  portugal: 'Portugal',
  romania: 'Romania',
  russia: 'Russia',
  saudiarabia: 'Saudi Arabia',
  senegal: 'Senegal',
  serbia: 'Serbia',
  slovakia: 'Slovakia',
  southkorea: 'South Korea',
  spain: 'Spain',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  tunisia: 'Tunisia',
  turkey: 'Turkey',
  ukraine: 'Ukraine',
  uruguay: 'Uruguay',
  wales: 'Wales',

  luzhniki: 'Luzhniki stafium, Moscow',
  otkritie: 'Otkritie Arena, Moscow',
  krestovsky: 'Krestovsky Stadium, Saint Petersburg',
  fisht: 'Fisht Olympic Stadium, Sochi',
  kazan: 'Kazan Arena, Kazan',
  volgograd: 'Volgograd Arena, Volgograd',
  kaliningrad: 'Kaliningrad Stadium, Kaliningrad',
  ekaterinburg: 'Ekaterinburg Arena, Yekaterinburg',
  mordovia: 'Mordovia Arena, Saransk',
  'nizhny-novgorod': 'Nizhny Novgorod Stadium, Nizhny Novgorod',
  rostov: 'Rostov Arena, Rostov-on-Don',
  cosmos: 'Cosmos Arena, Samara',

  helpL1: `Amis Footix, le but de ce Lotofoot est de pronostiquer le vainqueur et le score final (prolongations incluses) de chaque match de l'Euro. ` +
    `Dans le cas d'un match à élimination directe, si vous pronostiquez un match nul, vous devez aussi préciser quelle est l'équipe que vous voyez victorieuse à l'issue des tirs aux buts.`,
  helpL2: `Pour chaque match, votre score dépendra du stade de la compétition (groups, quarts de finale...) et de la qualité de votre pronostic (bon vainqueur, bonne différence de buts, score exact). Les points mis en jeu sont :`,
  helpL6: `Les pronostics peuvent être modifiés jusqu'au début des match. Bonne chance !`,
  helpLabel1: 'Right winner',
  helpLabel2: 'Right winner & goal difference',
  helpLabel3: 'Right winner & score',
};
