export default {
  account: 'My account',
  actions: 'Actions',
  app: 'Application',
  allPredictions: 'All bets',
  all: 'All',

  back: 'Go back',
  backHome: 'Back to homepage',

  cancel: 'Cancel',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Create',
  createAccount: 'Create my account',
  clickToPredict: 'Click to bet',

  delete: 'Delete',
  description: 'Description',
  dailyMaj: 'LOTOFOOT',

  eightFinal: 'Eighth finals',
  errorPageL1: 'An error occurred while viewing this page...',
  errorPageL2: 'Back to homepage',

  final: 'Final',
  firstname: 'First name',
  finished: 'Finished',
  forgottenPassword: 'Forgotten password',
  finishedGain: 'This bet earns you',

  games: 'Matches',
  game: 'Match',
  group: 'Group',
  groups: 'Groups',
  gamesMini: 'Matches',

  help: 'Help',
  home: 'All matches',
  homeMini: 'Matches',

  inProgress: 'In Progress',
  inProgressGain: 'For now, this bet earns you',

  key: 'Key',
  knockoutPhase: 'Knockout Phase',

  lastname: 'Last name',
  logout: 'Logout',
  login: 'Sign in',

  menu: 'Menu',
  modify: 'Modify',
  myPrediction: 'My bet',

  notfoundPageL1: 'The page you requested is not available...',
  notfoundPageL2: 'Back to homepage',

  ok: 'OK',

  password: 'Password',
  predictions: 'Mes bets',
  point: 'point',
  points: 'points',

  quarterFinal: 'quarter Final',

  ranking: 'General ranking',
  rankingMini: 'Ranking',
  refresh: 'Refresh',
  required: '(required)',
  recoverInitTitle: 'Forgotten password',
  recoverInitText: 'Enter your e-mail address so we can send you a link to reset your password',
  recoverInitTitleOk: 'Check your emails',
  recoverInitTextOk: 'We successfully received your request. An email allowing you to reset your password has been sent to you at ',
  recoverInitTextOk2: 'Remember to check your spams.',
  resetPassword: 'Reset my password',
  recoverTitle: 'Choose a new password',
  rules: 'Rules',
  recoverSuccessTitle: 'Well received!',
  recoverSuccessText: 'Your password has been changed.',
  recoverSuccessAction: 'Go to the lotofoot',

  send: 'Send',
  semiFinal: 'Semi Final',
  sendFeedback: 'Send feedback',

  title: 'Title',
  toCome: 'Next',
  toPredict: 'À pronostiquer',
  tabToPredict: 'Tap to bet',
  tooLate: 'It\'s too late, you can\'t bet on this match anymore',
  tooLate2: 'It\'s too late, all bets are closed',

  email: 'Email',
  emailExample: 'example@me.com',

  validate: 'Confirm',

  ga: 'Group A',
  gb: 'Group B',
  gc: 'Group C',
  gd: 'Group D',
  ge: 'Group E',
  gf: 'Group F',

  p1: '1/8',
  p2: '1/4',
  p3: '1/2',
  p4: 'Final',

  a1: '1st Group A',
  a2: '2nd Group A',
  b1: '1st Group B',
  b2: '2nd Group B',
  c1: '1st Group C',
  c2: '2nd Group C',
  d1: '1st Group D',
  d2: '2nd Group D',
  e1: '1st Group E',
  e2: '2nd Group E',
  f1: '1st Group F',
  f2: '2nd Group F',

  acd3: '3rd Group A, C or D',
  bef3: '3rd Group B, E or F',
  cde3: '3rd Group C, D or E',
  abf3: '3rd Group A, B or F',

  v37: 'Winner match 37',
  v38: 'Winner match 38',
  v39: 'Winner match 39',
  v40: 'Winner match 40',
  v41: 'Winner match 41',
  v42: 'Winner match 42',
  v43: 'Winner match 43',
  v44: 'Winner match 44',
  v45: 'Winner match 45',
  v46: 'Winner match 46',
  v47: 'Winner match 47',
  v48: 'Winner match 48',
  v49: 'Winner match 49',
  v50: 'Winner match 50',

  albania: 'Albania',
  austria: 'Austria',
  belgium: 'Belgium',
  croatia: 'Croatia',
  czechrepublic: 'Czech Republic',
  england: 'England',
  france: 'France',
  germany: 'Germany',
  hungary: 'Hungary',
  iceland: 'Iceland',
  ireland: 'Ireland',
  italy: 'Italy',
  northernireland: 'Northern Ireland',
  poland: 'Poland',
  portugal: 'Portugal',
  romania: 'Romania',
  russia: 'Russia',
  slovakia: 'Slovakia',
  spain: 'Spain',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  turkey: 'Turkey',
  ukraine: 'Ukraine',
  wales: 'Wales',

  helpL1: `Amis Footix, le but de ce lotofoot est de pronostiquer le vainqueur et le score final (prolongations incluses) de chaque match de l'Euro. ` +
    `Dans le cas d'un match à élimination directe, si vous pronostiquez un match nul, vous devez aussi préciser quelle est l'équipe que vous voyez victorieuse à l'issue des tirs aux buts.`,
  helpL2: `Pour chaque match, votre score dépendra du stade de la compétition (groups, quarts de finale...) et de la qualité de votre pronostic (bon vainqueur, bonne différence de buts, score exact). Les points mis en jeu sont :`,
  helpL6: `Les pronostics peuvent être modifiés jusqu'au début des match. Bonne chance !`,
  helpLabel1: 'Right winner',
  helpLabel2: 'Right winner & goal difference',
  helpLabel3: 'Right winner & score',
};
