export default {
  language: 'en',

  account: 'My account',
  accountMini: 'Account',
  actions: 'Actions',
  app: 'Application',
  allPredictions: 'All bets',
  all: 'All',

  back: 'Go back',
  backHome: 'Back to homepage',

  cancel: 'Cancel',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Create',
  createAccount: 'Create my account',
  clickToPredict: 'Click to bet',
  contactEmail: 'hello@lotofoot.io',
  contactUs: 'Contact us',
  contribute: 'Contribute to this project',

  delete: 'Delete',
  description: 'Description',
  dailyMaj: 'LOTOFOOT',
  development: 'Development',

  eightFinal: 'Round of 32',
  errorPageL1: 'An error occurred while rendering this page...',
  errorPageL2: 'Back to homepage',

  final: 'Final',
  firstname: 'First name',
  finished: 'Finished',
  forgottenPassword: 'Forgot your password?',
  finishedGain: 'This bet gives you',

  games: 'Matches',
  game: 'Match',
  group: 'Group',
  groups: 'Groups',
  gamesMini: 'Matches',

  help: 'Help',
  helpMini: 'Help',
  home: 'All matches',
  homeMini: 'Matches',

  inProgress: 'In Progress',
  inProgressGain: 'For now, this bet gives you',
  illustrations: 'Illustrations',

  key: 'Key',
  knockoutPhase: 'Knockout Phase',

  lastname: 'Last name',
  logout: 'Logout',
  login: 'Log in',

  menu: 'Menu',
  modify: 'Edit',
  myPrediction: 'My bet',

  notfoundPageL1: 'The page you requested is not available...',
  notfoundPageL2: 'Back to homepage',

  ok: 'OK',

  password: 'Password',
  predictions: 'My bets',
  point: 'point',
  points: 'points',

  quarterFinal: 'Quarter-Final',

  ranking: 'General ranking',
  rankingMini: 'Ranking',
  refresh: 'Refresh',
  required: '(required)',
  recoverInitTitle: 'Forgotten password',
  recoverInitText: 'Enter your e-mail address so that we can send you a link to reset your password',
  recoverInitTitleOk: 'Check your emails',
  recoverInitTextOk: 'We successfully received your request. An email allowing you to reset your password has been sent to you at ',
  recoverInitTextOk2: 'Remember to check your spams.',
  resetPassword: 'Reset my password',
  recoverTitle: 'Choose a new password',
  rules: 'Rules',
  recoverSuccessText: 'Your password has been changed.',
  recoverSuccessAction: 'Go to the Lotofoot',
  registerSuccessText: 'Your account has been created.',
  registerSuccessAction: 'Go to the Lotofoot',

  send: 'Send',
  semiFinal: 'Semi-Final',
  sendFeedback: 'Send feedback',
  signUp: 'Sign up',

  title: 'Title',
  toCome: 'Next',
  toPredict: 'Left to bet',
  tabToPredict: 'Tap to bet',
  tooLate: 'It\'s too late, you can\'t bet on this match anymore',
  tooLate2: 'It\'s too late, all bets are closed',

  email: 'Email',
  emailExample: 'example@me.com',

  validate: 'Confirm',

  wellReceived: 'Well received!',

  yourRanking: 'Ranking according to you',

  ga: 'Group A',
  gb: 'Group B',
  gc: 'Group C',
  gd: 'Group D',
  ge: 'Group E',
  gf: 'Group F',
  gg: 'Group G',
  gh: 'Group H',

  p1: '1/8',
  p2: '1/4',
  p3: '1/2',
  p4: 'Final',

  a1: '1st Group A',
  a2: '2nd Group A',
  b1: '1st Group B',
  b2: '2nd Group B',
  c1: '1st Group C',
  c2: '2nd Group C',
  d1: '1st Group D',
  d2: '2nd Group D',
  e1: '1st Group E',
  e2: '2nd Group E',
  f1: '1st Group F',
  f2: '2nd Group F',
  g1: '1st Group G',
  g2: '2nd Group G',
  h1: '1st Group H',
  h2: '2nd Group H',

  acd3: '3rd Group A, C or D',
  bef3: '3rd Group B, E or F',
  cde3: '3rd Group C, D or E',
  abf3: '3rd Group A, B or F',

  w37: 'Winner #37',
  w38: 'Winner #38',
  w39: 'Winner #39',
  w40: 'Winner #40',
  w41: 'Winner #41',
  w42: 'Winner #42',
  w43: 'Winner #43',
  w44: 'Winner #44',
  w45: 'Winner #45',
  w46: 'Winner #46',
  w47: 'Winner #47',
  w48: 'Winner #48',
  w49: 'Winner #49',
  w50: 'Winner #50',
  w51: 'Winner #51',
  w52: 'Winner #52',
  w53: 'Winner #53',
  w54: 'Winner #54',
  w55: 'Winner #55',
  w56: 'Winner #56',
  w57: 'Winner #57',
  w58: 'Winner #58',
  w59: 'Winner #59',
  w60: 'Winner #60',
  w61: 'Winner #61',
  w62: 'Winner #62',
  l61: 'Loser #61',
  l62: 'Loser #62',

  albania: 'Albania',
  argentina: 'Argentina',
  australia: 'Australia',
  austria: 'Austria',
  belgium: 'Belgium',
  brazil: 'Brazil',
  colombia: 'Colombia',
  costarica: 'Costa Rica',
  croatia: 'Croatia',
  czechrepublic: 'Czech Republic',
  denmark: 'Denmark',
  egypt: 'Egypt',
  england: 'England',
  france: 'France',
  germany: 'Germany',
  hungary: 'Hungary',
  iceland: 'Iceland',
  iran: 'Iran',
  ireland: 'Ireland',
  italy: 'Italy',
  japan: 'Japan',
  mexico: 'Mexico',
  morocco: 'Morocco',
  nigeria: 'Nigeria',
  northernireland: 'Northern Ireland',
  panama: 'Panama',
  peru: 'Peru',
  poland: 'Poland',
  portugal: 'Portugal',
  romania: 'Romania',
  russia: 'Russia',
  saudiarabia: 'Saudi Arabia',
  senegal: 'Senegal',
  serbia: 'Serbia',
  slovakia: 'Slovakia',
  southkorea: 'South Korea',
  spain: 'Spain',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  tunisia: 'Tunisia',
  turkey: 'Turkey',
  ukraine: 'Ukraine',
  uruguay: 'Uruguay',
  wales: 'Wales',

  luzhniki: 'Luzhniki stadium, Moscow',
  otkritie: 'Otkritie Arena, Moscow',
  krestovsky: 'Krestovsky Stadium, Saint Petersburg',
  fisht: 'Fisht Olympic Stadium, Sochi',
  kazan: 'Kazan Arena, Kazan',
  volgograd: 'Volgograd Arena, Volgograd',
  kaliningrad: 'Kaliningrad Stadium, Kaliningrad',
  ekaterinburg: 'Ekaterinburg Arena, Yekaterinburg',
  mordovia: 'Mordovia Arena, Saransk',
  'nizhny-novgorod': 'Nizhny Novgorod Stadium, Nizhny Novgorod',
  rostov: 'Rostov Arena, Rostov-on-Don',
  cosmos: 'Cosmos Arena, Samara',

  helpL1: `Dear Footix, the aim of the game is to guess the winner and the final score (overtime included) of each matches. ` +
    `In the case of a knockout match for which you predict a draw, you must specify which team you see victorious after the penalty shoot-out.`,
  helpL2: `For each bet, your score will depend on the stage of the competition (groups, round of 32, semi-final, ...) and the quality of your prediction (right winner, right goal difference, right score) :`,
  helpL3: `Bets can be changed until the beginning of the match. Good luck!`,
  helpL4: `Any question? contact us at `,
  helpLabel1: 'Right winner',
  helpLabel2: 'Right winner & goal difference',
  helpLabel3: 'Right winner & score',
};
