export default {
  account: 'Mon compte',
  actions: 'Actions',
  app: 'Application',
  allPredictions: 'Tous les pronostics',
  all: 'Tous',

  back: 'Revenez en arrière',
  backHome: 'Retour à l\'accueil',

  cancel: 'Annuler',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Créer',
  createAccount: 'Créer mon compte',
  clickToPredict: 'Cliquez pour pronostiquer',
  contactUs: 'Contactez-nous',

  delete: 'Supprimer',
  description: 'Description',
  dailyMaj: 'LOTOFOOT',
  development: 'Développement',
  contribute: 'Contrubuez au projet',

  eightFinal: 'Huitième de finale',
  errorPageL1: 'Une erreur est survenue lors de l\'affichage de cette page...',
  errorPageL2: 'Retourner à l\'accueil',

  final: 'Finale',
  firstname: 'Prénom',
  finished: 'Terminé',
  forgottenPassword: 'Mot de passe oublié',
  finishedGain: 'Ce pronostic vous rapporte',

  games: 'Matchs',
  game: 'Match',
  group: 'Groupe',
  groups: 'Groupes',
  gamesMini: 'Matchs',

  help: 'Aide',
  helpMini: 'Aide',
  home: 'Tous les matchs',
  homeMini: 'Matchs',

  inProgress: 'En cours',
  inProgressGain: 'Pour l\'instant, ce pronostic vous rapporte',
  illustrations: 'Illustrations',

  key: 'Clé',
  knockoutPhase: 'Phase finale',

  lastname: 'Nom',
  logout: 'Se déconnecter',
  login: 'Connexion',

  menu: 'Menu',
  modify: 'Modifier',
  myPrediction: 'Mon pronostic',

  notfoundPageL1: 'La page que vous avez demandée n\'est pas disponible...',
  notfoundPageL2: 'Retourner à l\'accueil',

  ok: 'OK',

  password: 'Mot de passe',
  predictions: 'Mes pronostics',
  point: 'point',
  points: 'points',

  quarterFinal: 'Quart de finale',

  ranking: 'Classement général',
  rankingMini: 'Classement',
  refresh: 'Recharger la page',
  required: '(requis)',
  recoverInitTitle: 'Mot de passe oublié',
  recoverInitText: 'Saisissez votre adresse e-mail pour que nous puissions vous envoyer un lien permettant de réinitialiser votre mot de passe',
  recoverInitTitleOk: 'Consultez vos emails',
  recoverInitTextOk: 'Nous avons bien reçu votre demande. Un email vous permettant de réinitialiser votre mot de passe vous a été envoyé à l\'adresse ',
  recoverInitTextOk2: 'Pensez à consulter les spams/courriers indésirables.',
  resetPassword: 'Réinitialiser mon mot de passe',
  recoverTitle: 'Choisissez un nouveau mot de passe',
  rules: 'Règles du jeu',
  recoverSuccessText: 'Votre mot de passe a été modifié.',
  recoverSuccessAction: 'Accéder au Lotofoot',
  registerSuccessText: 'Votre compte a été créé.',
  registerSuccessAction: 'Accéder au Lotofoot',

  send: 'Envoyer',
  semiFinal: 'Demi finale',
  sendFeedback: 'Envoyer un feedback',
  signUp: 'Inscription',

  title: 'Titre',
  toCome: 'À venir',
  toPredict: 'À pronostiquer',
  tabToPredict: 'Tapez pour pronostiquer',
  tooLate: 'Il est trop tard, vous ne pouvez plus parier sur ce match',
  tooLate2: 'Il est trop tard, les paris sont fermés',

  email: 'Email',
  emailExample: 'adresse@me.com',

  validate: 'Valider',

  wellReceived: 'Bien reçu !',

  ga: 'Groupe A',
  gb: 'Groupe B',
  gc: 'Groupe C',
  gd: 'Groupe D',
  ge: 'Groupe E',
  gf: 'Groupe F',
  gg: 'Groupe G',
  gh: 'Groupe H',

  p1: '1/8',
  p2: '1/4',
  p3: '1/2',
  p4: 'Finale',

  a1: '1e Groupe A',
  a2: '2e Groupe A',
  b1: '1e Groupe B',
  b2: '2e Groupe B',
  c1: '1e Groupe C',
  c2: '2e Groupe C',
  d1: '1e Groupe D',
  d2: '2e Groupe D',
  e1: '1e Groupe E',
  e2: '2e Groupe E',
  f1: '1e Groupe F',
  f2: '2e Groupe F',
  g1: '1e Groupe G',
  g2: '2e Groupe G',
  h1: '1e Groupe H',
  h2: '2e Groupe H',

  acd3: '3e Groupe A, C ou D',
  bef3: '3e Groupe B, E ou F',
  cde3: '3e Groupe C, D ou E',
  abf3: '3e Groupe A, B ou F',

  w37: 'Gagnant match 37',
  w38: 'Gagnant match 38',
  w39: 'Gagnant match 39',
  w40: 'Gagnant match 40',
  w41: 'Gagnant match 41',
  w42: 'Gagnant match 42',
  w43: 'Gagnant match 43',
  w44: 'Gagnant match 44',
  w45: 'Gagnant match 45',
  w46: 'Gagnant match 46',
  w47: 'Gagnant match 47',
  w48: 'Gagnant match 48',
  w49: 'Gagnant match 49',
  w50: 'Gagnant match 50',
  w51: 'Gagnant match 41',
  w52: 'Gagnant match 42',
  w53: 'Gagnant match 43',
  w54: 'Gagnant match 44',
  w55: 'Gagnant match 45',
  w56: 'Gagnant match 46',
  w57: 'Gagnant match 47',
  w58: 'Gagnant match 48',
  w59: 'Gagnant match 49',
  w60: 'Gagnant match 50',
  w61: 'Gagnant match 50',
  w62: 'Gagnant match 50',
  l61: 'Perdant match 50',
  l62: 'Perdant match 50',

  albania: 'Albanie',
  argentina: 'Argentine',
  australia: 'Australie',
  austria: 'Autriche',
  belgium: 'Belgique',
  brazil: 'Brésil',
  colombia: 'Colombie',
  costarica: 'Costa Rica',
  croatia: 'Croatie',
  czechrepublic: 'République Tchèque',
  denmark: 'Danemark',
  egypt: 'Égypte',
  england: 'Angleterre',
  france: 'France',
  germany: 'Allemagne',
  hungary: 'Hongrie',
  iceland: 'Islande',
  iran: 'Iran',
  ireland: 'République d\'Irlande',
  italy: 'Italie',
  japan: 'Japon',
  mexico: 'Mexique',
  morocco: 'Maroc',
  nigeria: 'Nigeria',
  northernireland: 'Irlande du Nord',
  panama: 'Panama',
  peru: 'Pérou',
  poland: 'Pologne',
  portugal: 'Portugal',
  romania: 'Roumanie',
  russia: 'Russie',
  saudiarabia: 'Arabie saoudite',
  southkorea: 'Corée du Sud',
  senegal: 'Sénégal',
  serbia: 'Serbie',
  slovakia: 'Slovaquie',
  spain: 'Espagne',
  sweden: 'Suède',
  switzerland: 'Suisse',
  tunisia: 'Tunisie',
  turkey: 'Turquie',
  ukraine: 'Ukraine',
  uruguay: 'Uruguay',
  wales: 'Pays de Galles',

  helpL1: `Amis Footix, le but de ce Lotofoot est de pronostiquer le vainqueur et le score final (prolongations incluses) de chaque match de l'Euro. ` +
    `Dans le cas d'un match à élimination directe, si vous pronostiquez un match nul, vous devez aussi préciser quelle est l'équipe que vous voyez victorieuse à l'issue des tirs aux buts.`,
  helpL2: `Pour chaque match, votre score dépendra du stade de la compétition (groupes, quarts de finale...) et de la qualité de votre pronostic (bon vainqueur, bonne différence de buts, score exact). Les points mis en jeu sont :`,
  helpL6: `Les pronostics peuvent être modifiés jusqu'au début des match. Bonne chance !`,
  helpLabel1: 'Bon gagnant',
  helpLabel2: 'Gagnant & bonne diff de buts',
  helpLabel3: 'Gagnant & bon score',
};
