import keyMirror from "keymirror";

const Actions = keyMirror({
  //// PUBLIC
  APIOK_PUBLIC_APPS: null,
  LOGIN_PENDING: null,
  LOGIN_SUCCESS: null,
  LOGIN_COOKIE_FOUND: null,
  LOGIN_UPDATE_CREDENTIALS: null,

  // HUBFRONT
  DIALOG_LOGIN_FAILURE: null,
  DIALOG_SHOW: null,
  DIALOG_SUBMIT: null,
  APPS_DIALOG_SWITCH: null,
  APPS_DIALOG_CLOSE: null,
  ACCOUNT_DIALOG_SWITCH: null,
  ACCOUNT_DIALOG_CLOSE: null,
  NAV_SWITCH: null,
  NAV_CLOSE: null,

  // RECOVER
  RECOVERINIT_INIT: null,
  RECOVERINIT_PENDING: null,
  RECOVERINIT_FAILED: null,
  RECOVERINIT_SUCCESS: null,
  RECOVER_INIT: null,
  RECOVER_INIT_FAILED: null,
  RECOVER_PENDING: null,
  RECOVER_FAILED: null,
  RECOVER_SUCCESS: null,


  //// STANDARD
  APIOK_MYACCOUNT: null,
  APIOK_MYAPPS: null,
  APIOK_MYACCOUNT_EDIT: null,
  MYACCOUNT_EDIT_FIRSTNAME: null,
  MYACCOUNT_EDIT_LASTNAME: null,
  MYACCOUNT_EDIT_DEPARTMENT: null,
  MYACCOUNT_EDIT_MOBILE: null,
  INIT_MYACCOUNTPSWD_EDIT: null,
  MYACCOUNT_EDIT_OLDPASSWORD: null,
  MYACCOUNT_EDIT_NEWPASSWORD: null,

  // HUBFRONT
  APIOK_REFAPPS: null,
  APIOK_REFGROUPS: null,


  //// EDITOR


  //// ADMIN
  // USER
  APIOK_USERS: null,
  APIOK_USER: null,
  INIT_USER_CREATE: null,
  APIOK_USER_EDIT: null,
  APIOK_USER_DELETE: null,
  USER_EDIT_USERNAME: null,
  USER_EDIT_PASSWORD: null,
  USER_EDIT_FIRSTNAME: null,
  USER_EDIT_LASTNAME: null,
  USER_EDIT_GROUP: null,
  USER_EDIT_COMPANY: null,
  USER_EDIT_DEPARTMENT: null,
  USER_EDIT_MOBILE: null,
  USER_EDIT_HASMEDIAMETRIE: null,
  USER_EDIT_HASPLURIMEDIA: null,
  USER_EDIT_HASSEEVIBES: null,
  USER_EDIT_HASKANTAR: null,
  USER_EDIT_HASKANTARVIDEO: null,
  USER_EDIT_HASHARRIS: null,
  USER_EDIT_ISADVERTISER: null,
  USERS_SORTTYPE_CHANGED: null,

  // AUTH
  APIOK_AUTHS: null,
  INIT_AUTH_CREATE: null,
  APIOK_AUTH_EDIT: null,
  APIOK_AUTH_DELETE: null,
  AUTH_EDIT_USERNAME: null,
  AUTH_EDIT_APP: null,
  AUTH_EDIT_ROLE: null,
  AUTHS_SORTTYPE_CHANGED: null,

  // APPS
  APIOK_APPS: null,
  APIOK_APP: null,
  APPS_SORTTYPE_CHANGED: null,

  // GROUPS
  APIOK_GROUPS: null,
  APIOK_GROUP: null,
  
  // PREF
  APIOK_PREFS: null,
  APIOK_PREF_DELETE: null,
  PREFS_SORTTYPE_CHANGED: null,

  // fluxible-router actions
  NAVIGATE_START: null,
  NAVIGATE_SUCCESS: null,
  NAVIGATE_FAILURE: null
});

export default Actions;
