const Labels = {
  account: 'Mon compte',
  actions: 'Actions',
  app: 'Application',
  cancel: 'Annuler',
  create: 'Créer',
  createAccount: 'Créer un compte',
  delete: 'Supprimer',
  description: 'Description',
  firstname: 'Prénom',
  forgottenPassword: 'Mot de passe oublié',
  games: 'Matchs',
  home: 'Accueil',
  key: 'Clé',
  lastname: 'Nom',
  logout: 'Se déconnecter',
  login: 'Connexion',
  modify: 'Modifier',
  password: 'Mot de passe',
  predictions: 'Pronostiques',
  ranking: 'Classement',
  refresh: 'Recharger la page',
  required: '(requis)',
  recoverInitTitle: 'MOT DE PASSE OUBLIÉ',
  recoverInitText: 'Saisissez votre adresse e-mail pour que nous puissions vous envoyer un lien permettant de réinitialiser votre mot de passe',
  recoverInitTitleOk: 'CONSULTEZ VOS EMAILS',
  recoverInitTextOk: 'Nous avons bien reçu votre demande. Un email vous permettant de réinitialiser votre mot de passe vous a été envoyé à l\'adresse ',
  resetPassword: 'Réinitialiser mon mot de passe',
  recoverTitle: 'CHOISISSEZ UN NOUVEAU MOT DE PASSE',
  send: 'Envoyer',
  title: 'Titre',
  username: 'Email',
  validate: 'Valider',
};

export default Labels;
