const Labels = {
  account: 'Mon compte',
  actions: 'Actions',
  app: 'Application',
  back: 'Revenez en arrière',
  backHome: 'Retour à l\'accueil',
  cancel: 'Annuler',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Créer',
  createAccount: 'Créer mon compte',
  delete: 'Supprimer',
  description: 'Description',
  firstname: 'Prénom',
  forgottenPassword: 'Mot de passe oublié',
  games: 'Matchs',
  home: 'Tous les matchs',
  homeMini: 'Matchs',
  key: 'Clé',
  lastname: 'Nom',
  logout: 'Se déconnecter',
  login: 'Connexion',
  modify: 'Modifier',
  password: 'Mot de passe',
  predictions: 'Mes pronostics',
  ranking: 'Classement général',
  rankingMini: 'Classement',
  refresh: 'Recharger la page',
  required: '(requis)',
  recoverInitTitle: 'MOT DE PASSE OUBLIÉ',
  recoverInitText: 'Saisissez votre adresse e-mail pour que nous puissions vous envoyer un lien permettant de réinitialiser votre mot de passe',
  recoverInitTitleOk: 'CONSULTEZ VOS EMAILS',
  recoverInitTextOk: 'Nous avons bien reçu votre demande. Un email vous permettant de réinitialiser votre mot de passe vous a été envoyé à l\'adresse ',
  resetPassword: 'Réinitialiser mon mot de passe',
  recoverTitle: 'CHOISISSEZ UN NOUVEAU MOT DE PASSE',
  send: 'Envoyer',
  title: 'Titre',
  username: 'Email',
  usernameExample: 'adresse@me.com',
  validate: 'Valider',

  a1: '1e Groupe A',
  a2: '2e Groupe A',
  b1: '1e Groupe B',
  b2: '2e Groupe B',
  c1: '1e Groupe C',
  c2: '2e Groupe C',
  d1: '1e Groupe D',
  d2: '2e Groupe D',
  e1: '1e Groupe E',
  e2: '2e Groupe E',
  f1: '1e Groupe F',
  f2: '2e Groupe F',

  acd3: '3e Groupe A, C ou D',
  bef3: '3e Groupe B, E ou F',
  cde3: '3e Groupe C, D ou E',
  abf3: '3e Groupe A, B ou F',

  v37: 'Gagnant match 37',
  v38: 'Gagnant match 38',
  v39: 'Gagnant match 39',
  v40: 'Gagnant match 40',
  v41: 'Gagnant match 41',
  v42: 'Gagnant match 42',
  v43: 'Gagnant match 43',
  v44: 'Gagnant match 44',
  v45: 'Gagnant match 45',
  v46: 'Gagnant match 46',
  v47: 'Gagnant match 47',
  v48: 'Gagnant match 48',
  v49: 'Gagnant match 49',
  v50: 'Gagnant match 50',
};

export default Labels;
