const MatchsData = [
  {
    id: 1,
    phase: 0,
    group: 'a',
    date: '2016-06-10',
    time: '21h00',
    stadium: 'Saint-Denis',
    channel: 'tf1',
    teamA: 'France',
    teamB: 'Roumanie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 2,
    phase: 0,
    group: 'a',
    date: '2016-06-11',
    time: '15h00',
    stadium: 'Lens',
    channel: 'tf1',
    teamA: 'Albanie',
    teamB: 'Suisse',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 3,
    phase: 0,
    group: 'b',
    date: '2016-06-11',
    time: '18h00',
    stadium: 'Bordeaux',
    channel: '',
    teamA: 'Pays de Galles',
    teamB: 'Slovaquie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 4,
    phase: 0,
    group: 'b',
    date: '2016-06-11',
    time: '21h00',
    stadium: 'Marseille',
    channel: 'm6',
    teamA: 'Angleterre',
    teamB: 'Russie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 5,
    phase: 0,
    group: 'd',
    date: '2016-06-12',
    time: '15h00',
    stadium: 'Paris',
    channel: 'tf1',
    teamA: 'Turquie',
    teamB: 'Croatie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 6,
    phase: 0,
    group: 'c',
    date: '2016-06-12',
    time: '18h00',
    stadium: 'Nice',
    channel: '',
    teamA: 'Pologne',
    teamB: 'Irlande du Nord',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 7,
    phase: 0,
    group: 'c',
    date: '2016-06-12',
    time: '21h00',
    stadium: 'Lille',
    channel: 'tf1',
    teamA: 'Allemagne',
    teamB: 'Ukraine',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 8,
    phase: 0,
    group: 'd',
    date: '2016-06-13',
    time: '15h00',
    stadium: 'Toulouse',
    channel: '',
    teamA: 'Espagne',
    teamB: 'République tchèque',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 9,
    phase: 0,
    group: 'e',
    date: '2016-06-13',
    time: '18h00',
    stadium: 'Saint-Etienne',
    channel: '',
    teamA: 'Irlande',
    teamB: 'Suede',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 10,
    phase: 0,
    group: 'e',
    date: '2016-06-13',
    time: '21h00',
    stadium: 'Lyon',
    channel: 'm6',
    teamA: 'Belgique',
    teamB: 'Italie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 11,
    phase: 0,
    group: 'f',
    date: '2016-06-14',
    time: '18h00',
    stadium: 'Bordeaux',
    channel: '',
    teamA: 'Autriche',
    teamB: 'Hongrie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 12,
    phase: 0,
    group: 'f',
    date: '2016-06-14',
    time: '21h00',
    stadium: 'Saint-Etienne',
    channel: '',
    teamA: 'Portugal',
    teamB: 'Islande',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 13,
    phase: 0,
    group: 'b',
    date: '2016-06-15',
    time: '15h00',
    stadium: 'Lille',
    channel: '',
    teamA: 'Russie',
    teamB: 'Slovaquie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 14,
    phase: 0,
    group: 'a',
    date: '2016-06-15',
    time: '18h00',
    stadium: 'Paris',
    channel: 'tf1',
    teamA: 'Roumanie',
    teamB: 'Suisse',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 15,
    phase: 0,
    group: 'a',
    date: '2016-06-15',
    time: '21h00',
    stadium: 'Marseille',
    channel: 'tf1',
    teamA: 'France',
    teamB: 'Albanie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 16,
    phase: 0,
    group: 'b',
    date: '2016-06-16',
    time: '15h00',
    stadium: 'Lens',
    channel: '',
    teamA: 'Angleterre',
    teamB: 'Pays de Galles',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 17,
    phase: 0,
    group: 'c',
    date: '2016-06-16',
    time: '18h00',
    stadium: 'Lyon',
    channel: '',
    teamA: 'Ukraine',
    teamB: 'Irlande du Nord',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 18,
    phase: 0,
    group: 'c',
    date: '2016-06-16',
    time: '21h00',
    stadium: 'Saint-Denis',
    channel: 'm6',
    teamA: 'Allemagne',
    teamB: 'Pologne',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 19,
    phase: 0,
    group: 'e',
    date: '2016-06-17',
    time: '15h00',
    stadium: 'Toulouse',
    channel: 'tf1',
    teamA: 'Italie',
    teamB: 'Suède',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 20,
    phase: 0,
    group: 'd',
    date: '2016-06-17',
    time: '18h00',
    stadium: 'Saint-Etiennes',
    channel: '',
    teamA: 'République Tchèque',
    teamB: 'Croatie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 21,
    phase: 0,
    group: 'd',
    date: '2016-06-17',
    time: '21h00',
    stadium: 'Nice',
    channel: 'm6',
    teamA: 'Espagne',
    teamB: 'Turquie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 22,
    phase: 0,
    group: 'e',
    date: '2016-06-18',
    time: '15h00',
    stadium: 'Bordeaux',
    channel: 'tf1',
    teamA: 'Belgique',
    teamB: 'Irlande',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 23,
    phase: 0,
    group: 'f',
    date: '2016-06-18',
    time: '18h00',
    stadium: 'Marseille',
    channel: '',
    teamA: 'Islande',
    teamB: 'Hongrie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 24,
    phase: 0,
    group: 'f',
    date: '2016-06-18',
    time: '21h00',
    stadium: 'Paris',
    channel: 'tf1',
    teamA: 'Portugal',
    teamB: 'Autriche',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 25,
    phase: 0,
    group: 'a',
    date: '2016-06-19',
    time: '21h00',
    stadium: 'Lyon',
    channel: 'm6',
    teamA: 'Roumanie',
    teamB: 'Albanie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 26,
    phase: 0,
    group: 'a',
    date: '2016-06-19',
    time: '21h00',
    stadium: 'Lille',
    channel: '',
    teamA: 'Suisse',
    teamB: 'France',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 27,
    phase: 0,
    group: 'b',
    date: '2016-06-20',
    time: '21h00',
    stadium: 'Toulouse',
    channel: 'tf1',
    teamA: 'Russie',
    teamB: 'Pays de Galles',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 28,
    phase: 0,
    group: 'b',
    date: '2016-06-20',
    time: '21h00',
    stadium: 'Saint-Etienne',
    channel: '',
    teamA: 'Slovaquie',
    teamB: 'Angleterre',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 29,
    phase: 0,
    group: 'c',
    date: '2016-06-21',
    time: '18h00',
    stadium: 'Marseille',
    channel: '',
    teamA: 'Ukraine',
    teamB: 'Pologne',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 30,
    phase: 0,
    group: 'c',
    date: '2016-06-21',
    time: '18h00',
    stadium: 'Paris',
    channel: '',
    teamA: 'Irlande du Nord',
    teamB: 'Allemagne',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 31,
    phase: 0,
    group: 'd',
    date: '2016-06-21',
    time: '21h00',
    stadium: 'Lens',
    channel: 'tf1',
    teamA: 'République Tchèque',
    teamB: 'Turquie',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 32,
    phase: 0,
    group: 'd',
    date: '2016-06-21',
    time: '21h00',
    stadium: 'Bordeaux',
    channel: '',
    teamA: 'Croatie',
    teamB: 'Espagne',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 33,
    phase: 0,
    group: 'f',
    date: '2016-06-22',
    time: '18h00',
    stadium: 'Saint-Denis',
    channel: '',
    teamA: 'Islande',
    teamB: 'Autriche',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 34,
    phase: 0,
    group: 'f',
    date: '2016-06-22',
    time: '18h00',
    stadium: 'Lyon',
    channel: '',
    teamA: 'Hongrie',
    teamB: 'Portugal',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 35,
    phase: 0,
    group: 'e',
    date: '2016-06-22',
    time: '21h00',
    stadium: 'Lille',
    channel: 'm6',
    teamA: 'Italie',
    teamB: 'Irlande',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 36,
    phase: 0,
    group: 'e',
    date: '2016-06-22',
    time: '21h00',
    stadium: 'Nice',
    channel: '',
    teamA: 'Suède',
    teamB: 'Belgique',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 37,
    phase: 1,
    date: '2016-06-25',
    time: '15h00',
    stadium: 'Saint-Étienne',
    channel: '',
    teamA: 'a2',
    teamB: 'c2',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 38,
    phase: 1,
    date: '2016-06-25',
    time: '18h00',
    stadium: 'Paris',
    channel: '',
    teamA: 'b1',
    teamB: 'acd3',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 39,
    phase: 1,
    date: '2016-06-25',
    time: '21h00',
    stadium: 'Lens',
    channel: '',
    teamA: 'd1',
    teamB: 'bef3',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 40,
    phase: 1,
    date: '2016-06-26',
    time: '15h00',
    stadium: 'Lyon',
    channel: '',
    teamA: 'a1',
    teamB: 'cde3',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 41,
    phase: 1,
    date: '2016-06-26',
    time: '18h00',
    stadium: 'Lille',
    channel: '',
    teamA: 'c1',
    teamB: 'abf3',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 42,
    phase: 1,
    date: '2016-06-26',
    time: '21h00',
    stadium: 'Toulouse',
    channel: '',
    teamA: 'f1',
    teamB: 'e2',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 43,
    phase: 1,
    date: '2016-06-27',
    time: '18h00',
    stadium: 'Saint-Denis',
    channel: '',
    teamA: 'e1',
    teamB: 'd2',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 44,
    phase: 1,
    date: '2016-06-27',
    time: '21h00',
    stadium: 'Nice',
    channel: '',
    teamA: 'b2',
    teamB: 'f2',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 45,
    phase: 2,
    date: '2016-06-30',
    time: '21h00',
    stadium: 'Marseille',
    channel: '',
    teamA: 'v37',
    teamB: 'v39',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 46,
    phase: 2,
    date: '2016-07-01',
    time: '21h00',
    stadium: 'Lille',
    channel: '',
    teamA: 'v38',
    teamB: 'v42',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 47,
    phase: 2,
    date: '2016-07-02',
    time: '21h00',
    stadium: 'Bordeaux',
    channel: '',
    teamA: 'v41',
    teamB: 'v43',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 48,
    phase: 2,
    date: '2016-07-03',
    time: '21h00',
    stadium: 'Saint-Denis',
    channel: '',
    teamA: 'v40',
    teamB: 'v44',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 49,
    phase: 3,
    date: '2016-07-06',
    time: '21h00',
    stadium: 'Lyon',
    channel: '',
    teamA: 'v45',
    teamB: 'v46',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 50,
    phase: 3,
    date: '2016-07-07',
    time: '21h00',
    stadium: 'Marseille',
    channel: '',
    teamA: 'v47',
    teamB: 'v48',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
  {
    id: 51,
    phase: 4,
    date: '2016-07-10',
    time: '21h00',
    stadium: 'Saint-Denis',
    channel: '',
    teamA: 'v49',
    teamB: 'v50',
    goalA: -1,
    goalB: -1,
    winner: '',
    tme: -1,
    pda: -1,
  },
];

export default MatchsData;
