const Labels = {
  account: 'Mon compte',
  actions: 'Actions',
  app: 'Application',
  allPredictions: 'Tous les pronostics',
  back: 'Revenez en arrière',
  backHome: 'Retour à l\'accueil',
  cancel: 'Annuler',
  chat: 'Chat',
  chatMini: 'Chat',
  create: 'Créer',
  createAccount: 'Créer mon compte',
  delete: 'Supprimer',
  description: 'Description',
  eightFinal: 'Huitième de finale',
  final: 'Finale',
  firstname: 'Prénom',
  finished: 'Terminé',
  forgottenPassword: 'Mot de passe oublié',
  games: 'Matchs',
  game: 'Match',
  group: 'Groupe',
  groups: 'Groupes',
  hasPaid: '✅  Cotisation à jour',
  hasNotPaid: '💲  Je dois 5€',
  help: 'Aide',
  home: 'Tous les matchs',
  homeMini: 'Matchs',
  inProgress: 'En cours',
  key: 'Clé',
  knockoutPhase: 'Phase finale',
  lastname: 'Nom',
  logout: 'Se déconnecter',
  login: 'Connexion',
  menu: 'Menu',
  modify: 'Modifier',
  ok: 'OK',
  password: 'Mot de passe',
  predictions: 'Mes pronostics',
  quarterFinal: 'Quart de finale',
  ranking: 'Classement général',
  rankingMini: 'Classement',
  refresh: 'Recharger la page',
  required: '(requis)',
  recoverInitTitle: 'Mot de passe oublié',
  recoverInitText: 'Saisissez votre adresse e-mail pour que nous puissions vous envoyer un lien permettant de réinitialiser votre mot de passe',
  recoverInitTitleOk: 'Consultez vos emails',
  recoverInitTextOk: 'Nous avons bien reçu votre demande. Un email vous permettant de réinitialiser votre mot de passe vous a été envoyé à l\'adresse ',
  resetPassword: 'Réinitialiser mon mot de passe',
  recoverTitle: 'Choisissez un nouveau mot de passe',
  rules: 'Règles du jeu',
  send: 'Envoyer',
  semiFinal: 'Demi finale',
  title: 'Titre',
  username: 'Email',
  usernameExample: 'adresse@me.com',
  validate: 'Valider',

  all: 'Tous',
  toCome: 'À venir',
  toPredict: 'À pronostiquer',
  clickToPredict: 'Cliquez pour pronostiquer',
  tabToPredict: 'Tapez pour pronostiquer',
  tooLate: 'Il est trop tard, vous ne pouvez plus parier sur ce match',
  myPrediction: 'Mon pronostic',
  inProgressGain: 'Pour l\'instant, ce pronostic vous rapporte',
  finishedGain: 'Ce pronostic vous rapporte',
  point: 'point',
  points: 'points',

  ga: 'Groupe A',
  gb: 'Groupe B',
  gc: 'Groupe C',
  gd: 'Groupe D',
  ge: 'Groupe E',
  gf: 'Groupe F',

  p1: '1/8',
  p2: '1/4',
  p3: '1/2',
  p4: 'Finale',

  a1: '1e Groupe A',
  a2: '2e Groupe A',
  b1: '1e Groupe B',
  b2: '2e Groupe B',
  c1: '1e Groupe C',
  c2: '2e Groupe C',
  d1: '1e Groupe D',
  d2: '2e Groupe D',
  e1: '1e Groupe E',
  e2: '2e Groupe E',
  f1: '1e Groupe F',
  f2: '2e Groupe F',

  acd3: '3e Groupe A, C ou D',
  bef3: '3e Groupe B, E ou F',
  cde3: '3e Groupe C, D ou E',
  abf3: '3e Groupe A, B ou F',

  v37: 'Gagnant match 37',
  v38: 'Gagnant match 38',
  v39: 'Gagnant match 39',
  v40: 'Gagnant match 40',
  v41: 'Gagnant match 41',
  v42: 'Gagnant match 42',
  v43: 'Gagnant match 43',
  v44: 'Gagnant match 44',
  v45: 'Gagnant match 45',
  v46: 'Gagnant match 46',
  v47: 'Gagnant match 47',
  v48: 'Gagnant match 48',
  v49: 'Gagnant match 49',
  v50: 'Gagnant match 50',

  albania: 'Albanie',
  austria: 'Autriche',
  belgium: 'Belgique',
  croatia: 'Croatie',
  england: 'Angleterre',
  france: 'France',
  germany: 'Allemagne',
  hungary: 'Hongrie',
  iceland: 'Islande',
  ireland: 'République d\'Irlande',
  italy: 'Italie',
  northernireland: 'Irlande du Nord',
  poland: 'Pologne',
  portugal: 'Portugal',
  romania: 'Roumanie',
  russia: 'Russie',
  slovakia: 'Slovaquie',
  spain: 'Espagne',
  sweden: 'Suède',
  switzerland: 'Suisse',
  czechrepublic: 'République Tchèque',
  turkey: 'Turquie',
  ukraine: 'Ukraine',
  wales: 'Pays de Galles',

  helpL1: `Amis Footix, le but de ce lotofoot est de pronostiquer le vainqueur et le score de chaque match de l'Euro. Nous tenons compte du score final du match, prolongations incluses. ` +
    `Dans le cas d'un match à élimination directe, si vous pronostiquez un match nul, vous devez aussi préciser quelle est l'équipe que vous voyez victorieuse à l'issue des tirs aux buts.`,
  helpL2: `Le nombre de points que vos pronostics vous rapportent dépend :`,
  helpL3: `- Du stade de la compétition auquel appartient le match (groupes, quarts de finale...)`,
  helpL4: `- De l'exactitude de votre pronostic (bon vainqueur, bon vainqueur et bonne différence de buts, bon vainqueur avec le score exact)`,
  helpL5: `Les points mis en jeu sont les suivants :`,
  helpL6: `Les pronostics peuvent être modifiés jusqu'au début du match. Bonne chance !`,
  helpLabel1: 'Bon gagnant',
  helpLabel2: 'Gagnant & bonne diff de buts',
  helpLabel3: 'Gagnant & bon score',
};

export default Labels;
